// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqTXukuHNxE1awrnqRIlRJhwu6rq7Wp_Y',
    appId: '1:205959038258:web:8e7b3ef84dbd8dc39c032b',
    messagingSenderId: '205959038258',
    projectId: 'teftef-auth',
    authDomain: 'teftef-auth.firebaseapp.com',
    storageBucket: 'teftef-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw09LmdBawWm2Z3yjIHI2SVF6f191yLqs',
    appId: '1:205959038258:android:e45de9c1a01597b39c032b',
    messagingSenderId: '205959038258',
    projectId: 'teftef-auth',
    storageBucket: 'teftef-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHK7m1N8iCDsamWFiBgij2RsNNF79jCtA',
    appId: '1:205959038258:ios:8016a28a846abecf9c032b',
    messagingSenderId: '205959038258',
    projectId: 'teftef-auth',
    storageBucket: 'teftef-auth.firebasestorage.app',
    iosBundleId: 'com.example.teftef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHK7m1N8iCDsamWFiBgij2RsNNF79jCtA',
    appId: '1:205959038258:ios:8016a28a846abecf9c032b',
    messagingSenderId: '205959038258',
    projectId: 'teftef-auth',
    storageBucket: 'teftef-auth.firebasestorage.app',
    iosBundleId: 'com.example.teftef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqTXukuHNxE1awrnqRIlRJhwu6rq7Wp_Y',
    appId: '1:205959038258:web:5e82e86c4f81f29a9c032b',
    messagingSenderId: '205959038258',
    projectId: 'teftef-auth',
    authDomain: 'teftef-auth.firebaseapp.com',
    storageBucket: 'teftef-auth.firebasestorage.app',
  );
}
